//! Compatibility layer for mounting Cordis plugins in rutis applications.
//!
//! Everything here uses public rutis API only. Generated bindings cover typed
//! value methods and follow service replacement; the shared RPC layer also
//! supports owned callbacks and async results. See
//! `docs/design-protocol-plugin-mount.md` for the covered surface and the
//! boundary rules for Cordis plugins.

pub mod build;

/// Wire protocol version. The Node runtime package declares the version it
/// speaks as `rutisProtocol` in its package.json; builds check they match.
pub const PROTOCOL: u32 = 1;

/// Environment variable naming the npm project the mounts load from, for a
/// binary running against a deployed copy of it.
pub const ROOT_VARIABLE: &str = "RUTIS_INTEROP_ROOT";

/// The npm project the generated mounts load their runtime and plugins from:
/// [`ROOT_VARIABLE`] when set, else `built`, where it was at build time.
pub fn npm_root(built: &str) -> std::path::PathBuf {
    std::env::var_os(ROOT_VARIABLE)
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| built.into())
}

/// Declare every mount configured in `[package.metadata.rutis-interop]` as a
/// module (generated by `build::from_manifest`), e.g. `credentials::Plugin`.
#[macro_export]
macro_rules! include_mounts {
    () => {
        // Mounts are generated on Unix only; elsewhere there is nothing to include.
        #[cfg(unix)]
        include!(concat!(env!("OUT_DIR"), "/rutis_interop_mounts.rs"));
    };
}
#[cfg(unix)]
mod events;
#[cfg(unix)]
mod objects;
#[cfg(unix)]
mod process;
#[cfg(unix)]
mod projection;
// The session layer runs on any channel; only launching processes and the
// Unix socket channel are platform specific.
mod protocol;
pub mod rpc;
#[cfg(unix)]
mod runtime;
#[cfg(unix)]
pub mod server;

#[cfg(unix)]
pub use events::{EmitToCordis, EventSink, Events};
#[cfg(unix)]
pub use objects::{arg, decode_value, JsError, ObjectRef, RemoteFunction};
#[cfg(unix)]
pub use process::{Host, HostDispatch, Mount, Process, ServiceEvents};
#[cfg(unix)]
pub use projection::Projection;
#[cfg(unix)]
pub use runtime::{host_key, CordisRuntime, CordisRuntimePlugin, RuntimeHandle, RuntimeState};
pub use rutis_channel;
pub use serde;
pub use serde_json;

/// A Rust failure as the peer sees it: a `RustError`.
pub fn native_error(error: impl std::fmt::Display) -> Error {
    Error::Remote {
        name: "RustError".into(),
        message: error.to_string(),
        graph: None,
    }
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum Error {
    #[error("{0}")]
    Transport(String),
    #[error("{name}: {message}")]
    Remote {
        name: String,
        message: String,
        graph: Option<serde_json::Value>,
    },
    #[error("synchronous wait cycle: {0}")]
    SyncWaitCycle(String),
    #[error("invalid binding value: {0}")]
    Value(String),
}

impl From<Error> for rutis::CordisError {
    fn from(error: Error) -> Self {
        Self::PluginFailed(Box::new(error))
    }
}

pub fn decode<T: serde::de::DeserializeOwned>(value: serde_json::Value) -> Result<T, Error> {
    serde_json::from_value(value).map_err(|error| Error::Value(error.to_string()))
}

/// Deserialize a field that TypeScript declares both optional and nullable
/// (`key?: T | null`) as `Option<Option<T>>`: a missing field is `None`, an
/// explicit `null` is `Some(None)`. Use with `#[serde(default)]`.
#[cfg(unix)]
pub fn nullable<'de, D, T>(deserializer: D) -> Result<Option<Option<T>>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <Option<T> as serde::Deserialize>::deserialize(deserializer).map(Some)
}

/// Encode an optional argument: `None` is passed as JS `undefined`, not
/// `null`, so defaults and `=== undefined` checks behave as in native calls.
#[cfg(unix)]
pub fn optional<T: serde::Serialize>(value: Option<T>) -> Result<rpc::Value, Error> {
    match value {
        Some(value) => arg(&value),
        None => Ok(rpc::Value::Undefined),
    }
}
