// The release train: the packages released together at one version.
//   node scripts/train.mjs            print the version; fail on a mismatch
//   node scripts/train.mjs v0.3.0     also fail unless the version is 0.3.0
import { readFileSync } from 'node:fs'

const root = new URL('../', import.meta.url)
const read = path => readFileSync(new URL(path, root), 'utf8')
const json = path => JSON.parse(read(path))
const cargo = path => read(path).match(/^version = "([^"]+)"/m)?.[1]
const pyproject = path => read(path).match(/^version = "([^"]+)"/m)?.[1]
const dependency = (path, name) => read(path).match(new RegExp(`^${name} = \\{[^}]*version = "([^"]+)"`, 'm'))?.[1]

const versions = {
  'crates/rutis-bridge': cargo('crates/rutis-bridge/Cargo.toml'),
  'crates/rutis-loader': cargo('crates/rutis-loader/Cargo.toml'),
  'crates/rutis-host': cargo('crates/rutis-host/Cargo.toml'),
  'npm @arcships/rutis': json('node/rutis/package.json').version,
  'npm @arcships/rutis-runtime': json('node/rutis-runtime/package.json').version,
  'npm @arcships/rutis-host': json('node/rutis-host/package.json').version,
  'pypi rutis': pyproject('python/rutis/pyproject.toml'),
}
const host = json('node/rutis-host/package.json')
const references = {
  'rutis-loader → rutis-bridge': dependency('crates/rutis-loader/Cargo.toml', 'rutis-bridge'),
  'rutis-host → rutis-bridge': dependency('crates/rutis-host/Cargo.toml', 'rutis-bridge'),
  'rutis-host → rutis-loader': dependency('crates/rutis-host/Cargo.toml', 'rutis-loader'),
  '@arcships/rutis-host → @arcships/rutis-runtime': host.dependencies['@arcships/rutis-runtime'],
  ...Object.fromEntries(Object.entries(host.optionalDependencies).map(([name, version]) => [`@arcships/rutis-host → ${name}`, version])),
}

// The platform packages (@arcships/rutis-host-<platform>-<arch>) are generated by
// node/rutis-host/scripts/platform-package.mjs with `version: host.version` and published
// verbatim; node/rutis-host/package.json lists them in optionalDependencies. Checking that
// `npm @arcships/rutis-host` and its optionalDependencies match the train therefore also
// guarantees the platform packages are at the train version.
const version = versions['crates/rutis-bridge']
const wrong = Object.entries({ ...versions, ...references })
  .filter(([, v]) => v !== version)
  .map(([what, found]) => `${what} is ${found}, not ${version}`)
// The PyPI rutis-host takes rutis within the train's minor version.
const [major, minor] = version.split('.').map(Number)
const range = major === 0 ? `rutis>=0.${minor},<0.${minor + 1}` : `rutis>=${major},<${major + 1}`
if (!read('crates/rutis-host/pyproject.toml').includes(`"${range}"`)) wrong.push(`pypi rutis-host must depend on "${range}"`)
const tag = process.argv[2]
if (tag && tag !== `v${version}`) wrong.push(`the tag is ${tag}, but the train is at ${version}`)
if (wrong.length) {
  for (const line of wrong) console.error(line)
  process.exit(1)
}
console.log(version)
